import React, { useEffect, useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { useToast } from './Toast';
import { 
  AlertTriangle, 
  Download, 
  Eye, 
  Volume2, 
  ShieldAlert, 
  CheckCircle, 
  FileText, 
  Sparkles,
  Info,
  X
} from 'lucide-react';

export default function FlaggedMediaViewer({ 
  contentType, 
  originalFile, 
  originalUrl, 
  textContent, 
  verificationData, 
  report, 
  onClose 
}) {
  const { showToast } = useToast();
  const [activeView, setActiveView] = useState('flagged'); // 'flagged' | 'original'
  const [flaggedImageUrl, setFlaggedImageUrl] = useState(null);
  const canvasRef = useRef(null);

  const isAI = (report?.aiProbability ?? verificationData?.result ?? 0) >= 45;
  const aiScore = report?.aiProbability ?? Math.round(verificationData?.result ?? 0);
  const humanScore = 100 - aiScore;
  const verificationId = report?.verificationId || `TL-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
  const watermarkLabel = isAI ? '⚠ AI GENERATED' : '⚠ VERIFIED AUTHENTIC';
  const themeColor = isAI ? '#ef4444' : '#10b981';

  // Generate Flagged Watermarked Image on Canvas
  useEffect(() => {
    if (contentType === 'image' && (originalFile || originalUrl)) {
      const img = new Image();
      img.crossOrigin = 'anonymous';

      if (originalFile) {
        img.src = URL.createObjectURL(originalFile);
      } else if (originalUrl) {
        img.src = originalUrl;
      }

      img.onload = () => {
        const canvas = canvasRef.current;
        if (!canvas) return;

        const ctx = canvas.getContext('2d');
        const width = img.width || 800;
        const height = img.height || 600;

        canvas.width = width;
        const footerHeight = Math.max(80, Math.round(height * 0.12));
        canvas.height = height + footerHeight;

        // 1. Draw Original Image
        ctx.drawImage(img, 0, 0, width, height);

        // 2. Draw High-Visibility Diagonal Watermark
        ctx.save();
        ctx.translate(width / 2, height / 2);
        ctx.rotate((-30 * Math.PI) / 180);

        const fontSize = Math.max(36, Math.round(width * 0.085));
        ctx.font = `900 ${fontSize}px system-ui, -apple-system, sans-serif`;
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';

        const stripHeight = fontSize * 1.6;
        ctx.fillStyle = isAI ? 'rgba(127, 29, 29, 0.75)' : 'rgba(6, 78, 59, 0.75)';
        ctx.fillRect(-width, -stripHeight / 2, width * 2, stripHeight);

        ctx.strokeStyle = isAI ? '#ef4444' : '#10b981';
        ctx.lineWidth = 4;
        ctx.beginPath();
        ctx.moveTo(-width, -stripHeight / 2);
        ctx.lineTo(width, -stripHeight / 2);
        ctx.moveTo(-width, stripHeight / 2);
        ctx.lineTo(width, stripHeight / 2);
        ctx.stroke();

        ctx.strokeStyle = '#000000';
        ctx.lineWidth = Math.max(8, Math.round(width * 0.012));
        ctx.strokeText(watermarkLabel, 0, 0);

        ctx.shadowColor = '#000000';
        ctx.shadowBlur = 18;
        ctx.shadowOffsetX = 4;
        ctx.shadowOffsetY = 6;

        ctx.fillStyle = isAI ? '#dc2626' : '#10b981';
        ctx.fillText(watermarkLabel, 0, 0);

        ctx.restore();

        // 3. Draw Verification Footer Banner
        const footerY = height;
        ctx.fillStyle = 'rgba(11, 15, 25, 0.94)';
        ctx.fillRect(0, footerY, width, footerHeight);

        ctx.strokeStyle = themeColor;
        ctx.lineWidth = 3;
        ctx.beginPath();
        ctx.moveTo(0, footerY);
        ctx.lineTo(width, footerY);
        ctx.stroke();

        ctx.fillStyle = '#ffffff';
        ctx.font = `800 ${Math.max(13, Math.round(width * 0.022))}px system-ui, sans-serif`;
        ctx.textAlign = 'left';
        ctx.fillText(`TruthLens AI Verification Report [ID: ${verificationId}]`, 20, footerY + 30);

        ctx.fillStyle = '#94a3b8';
        ctx.font = `600 ${Math.max(11, Math.round(width * 0.018))}px system-ui, sans-serif`;
        ctx.fillText(`AI Score: ${aiScore}% | Human: ${humanScore}% | Verdict: ${isAI ? 'AI Generated Media' : 'Authentic Media'} | Date: ${new Date().toLocaleString()}`, 20, footerY + 56);

        try {
          const flaggedUrl = canvas.toDataURL('image/png');
          setFlaggedImageUrl(flaggedUrl);
        } catch (e) {
          console.warn('Canvas export failed:', e);
        }
      };
    }
  }, [contentType, originalFile, originalUrl, isAI, aiScore]);

  // Audio Spoken Warning Overlay (every 12s)
  useEffect(() => {
    let audioTimer = null;
    if (contentType === 'audio' && isAI) {
      audioTimer = setInterval(() => {
        if ('speechSynthesis' in window) {
          const msg = new SpeechSynthesisUtterance("Warning. This audio has been flagged as potentially AI generated by TruthLens AI.");
          msg.rate = 1.0;
          msg.volume = 0.55;
          window.speechSynthesis.speak(msg);
        }
      }, 12000);
    }
    return () => {
      if (audioTimer) clearInterval(audioTimer);
      if ('speechSynthesis' in window) window.speechSynthesis.cancel();
    };
  }, [contentType, isAI]);

  // Handle Downloads
  const downloadFlaggedCopy = () => {
    if (contentType === 'image') {
      if (flaggedImageUrl) {
        const link = document.createElement('a');
        link.href = flaggedImageUrl;
        link.download = `FLAGGED_TRUTHLENS_${originalFile?.name || 'image.png'}`;
        link.click();
        showToast('Watermarked media copy downloaded', 'success');
      }
    } else if (contentType === 'text') {
      const flaggedText = `[FLAGGED CONTENT COPY - TRUTHLENS AI VERIFICATION]\nVERDICT: ${isAI ? 'AI GENERATED (SYNTHETIC)' : 'AUTHENTIC'}\nAI SCORE: ${aiScore}% | ID: ${verificationId}\nTIMESTAMP: ${new Date().toLocaleString()}\n--------------------------------------------------\n${textContent}`;
      const blob = new Blob([flaggedText], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `FLAGGED_TRUTHLENS_REPORT_${verificationId}.txt`;
      link.click();
      showToast('Flagged report copy downloaded', 'success');
    }
  };

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 99999,
        background: 'rgba(3, 7, 18, 0.88)',
        backdropFilter: 'blur(16px)',
        WebkitBackdropFilter: 'blur(16px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '20px'
      }}
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="glass-card"
        style={{
          width: '100%',
          maxWidth: '780px',
          maxHeight: '90vh',
          overflowY: 'auto',
          borderRadius: '24px',
          border: `1.5px solid ${themeColor}`,
          padding: '28px'
        }}
      >
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', paddingBottom: '16px', borderBottom: '1px solid var(--glass-border)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <AlertTriangle style={{ width: 24, height: 24, color: themeColor }} />
            <h3 style={{ fontSize: '1.25rem', fontWeight: 900, color: 'var(--text-primary)' }}>
              Watermarked Forensic Inspection Viewer
            </h3>
          </div>

          <button onClick={onClose} className="apple-glass-button" style={{ borderRadius: '50%', padding: '8px' }}>
            <X style={{ width: 18, height: 18 }} />
          </button>
        </div>

        {/* View Switcher */}
        <div style={{ display: 'flex', gap: '10px', marginBottom: '20px' }}>
          <button
            onClick={() => setActiveView('flagged')}
            style={{
              flex: 1,
              padding: '10px',
              borderRadius: '12px',
              border: 'none',
              background: activeView === 'flagged' ? 'var(--apple-accent-gradient)' : 'var(--bg-dropzone)',
              color: activeView === 'flagged' ? '#ffffff' : 'var(--text-muted)',
              fontWeight: 800,
              cursor: 'pointer',
              fontSize: '0.85rem'
            }}
          >
            Watermarked Audit Copy
          </button>
        </div>

        {/* Image Preview Canvas */}
        {contentType === 'image' && (
          <div style={{ textAlign: 'center', marginBottom: '20px' }}>
            <canvas ref={canvasRef} style={{ display: 'none' }} />
            {flaggedImageUrl ? (
              <img
                src={flaggedImageUrl}
                alt="Flagged Watermark Preview"
                style={{ maxWidth: '100%', maxHeight: '420px', borderRadius: '18px', border: `1px solid ${themeColor}` }}
              />
            ) : (
              <div style={{ padding: '40px', color: 'var(--text-muted)' }}>Rendering high-visibility watermark...</div>
            )}
          </div>
        )}

        {/* Download Action */}
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px', marginTop: '20px' }}>
          <button onClick={downloadFlaggedCopy} className="apple-primary-button" style={{ padding: '10px 20px', fontSize: '0.85rem' }}>
            <Download style={{ width: 16, height: 16 }} /> Download Watermarked Copy
          </button>
        </div>
      </motion.div>
    </div>
  );
}
